### ISSUE TITLE
New version of tiny go 

### ISSUE THREAD

**Issue by gedw99** [genjidb/genji.js#3]
https://github.com/tinygo-org/tinygo/tree/v0.14.0

Worth trying again as it says it supports go modules and probably some other fixes

**Comment by gedw99** [comment]
https://github.com/tinygo-org/tinygo/tree/release-v0.16.0

Has about 50 changes. Might be worth trying this again..

**Comment by joe-getcouragenow** [comment]
https://github.com/tinygo-org/tinygo/releases

**Comment by asdine** [comment]
Closing this as we are now using the latest version, and it works!
