### ISSUE TITLE
Indexeddb using golang not typescript

### ISSUE THREAD

**Issue by gedw99** [genjidb/genji.js#7]
There is a good golang indexeddb lib that I have been playing with.

https://github.com/hack-pad/go-indexeddb

the reason I am raising this issue is to see if there is any interest in getting it working with genji.

you would then be able to build gui for web that is wasm based and have a genji dB.

If there is interest I could have a try at it in a branch as I have some spare time at the moment.

Let me know :)

**Comment by asdine** [comment]
Closing this issue as this repo is going to be archived. But thanks @gedw99 !
